- .github/workflows/crowdin.yml
Crowdin via GitHub Actions instead of Crowdin yml
TODO:
https://github.com/marketplace/actions/crowdin-action
> [WIP] Crowdin via GitHub Actions instead of Crowdin yml

- packages/smooth_app/lib/cards/category_cards/attribute_card.dart
- packages/smooth_app/lib/data_models/smooth_it_model.dart
- packages/smooth_app/lib/pages/personalized_ranking_page.dart
- packages/smooth_app/pubspec.yaml
* `personalized_ranking_page.dart`: added a `BottomNavigationBar`
* `pubspec.yaml`: removed `flutter_sticky_header` that we don't use anymore
* `smooth_it_model.dart`: refactoring for flexibility
> feature/#35 - tabs for all products+matching yes/maybe/no

- packages/smooth_app/lib/pages/personalized_ranking_page.dart
- packages/smooth_app/lib/themes/smooth_theme.dart
Here is a small improvement to the darkmode for the ranking_page.
> raking_page darkmode fine tuning

- packages/smooth_app/lib/database/group_product_query.dart
- packages/smooth_app/lib/database/keywords_product_query.dart
- packages/smooth_app/lib/pages/choose_page.dart
* `choose_page.dart`: now calling the searches with an additional language parameter
* `group_product_query.dart`: additional language parameter
* `keywords_product_query.dart`: additional language parameter
> bug/#72 - searches are now with the correct language

- packages/smooth_app/lib/database/dao_product.dart
> bug/#84 - fix of upsert statement + refactoring

- .github/workflows/crowdin.yml
I'm hoping it will solve the issue with Crowdin emptying the app_en.arb file of https://github.com/openfoodfacts/smooth-app/pull/59
> add upload_language: en to Crowdin GitHub action options

- packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart
- packages/smooth_app/lib/temp/user_preferences.dart
* `user_preferences.dart`: replaced HIDDEN with VISIBLE (at this stage of the project that's affordable)
* `user_preferences_view.dart`: added a `ListTile` with a trailing icon
> feature/#102 - visible expand/collapse arrow and collapsed as default in preferences

- packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
- packages/smooth_app/lib/data_models/product_list.dart
- packages/smooth_app/lib/data_models/user_preferences_model.dart
- packages/smooth_app/lib/database/dao_product_list.dart
- packages/smooth_app/lib/database/local_database.dart
- packages/smooth_app/lib/main.dart
- packages/smooth_app/lib/pages/list_page.dart
- packages/smooth_app/lib/pages/personalized_ranking_page.dart
- packages/smooth_app/lib/pages/product_list_page.dart
- packages/smooth_app/lib/pages/product_page.dart
- packages/smooth_app/lib/pages/product_query_page.dart
- packages/smooth_app/lib/pages/product_query_page_helper.dart
New files:
* `list_page.dart`: display the list of product lists
* `product_list_page.dart`: displays a product list
* `dao_product_list.dart`: added methods `delete` and `getAll`; refactored
* `local_database.dart`: implemented the `notifyListeners` method
* `main.dart`: replaced the "track" option with "lists" on the bottom menu
* `personalized_ranking_page.dart`: simplified the "sliver" effects with standard flutter behavior
* `product_list.dart`: added the "history" list and the database read-only fields
* `product_page.dart`: added the product to "history" every time the page is displayed; added a standard back button
* `product_query_page.dart`: refactored
* `product_query_page_helper.dart`: added methods to the helper class
> feature/#21_3 - display the list of product lists, added product history

- packages/smooth_app/lib/bottom_sheet_views/user_contribution_view.dart
- packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart
- packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
- packages/smooth_app/lib/data_models/match.dart
- packages/smooth_app/lib/data_models/smooth_it_model.dart
- packages/smooth_app/lib/pages/list_page.dart
- packages/smooth_app/lib/pages/personalized_ranking_page.dart
- packages/smooth_app/lib/pages/product_page.dart
- packages/smooth_app/lib/pages/profile_page.dart
- packages/smooth_ui_library/lib/widgets/smooth_card.dart
- packages/smooth_ui_library/lib/widgets/smooth_expandable_card.dart
New file:
* `smooth_card.dart`
* `attribute_list_expandable.dart`: added the non-collapsible and colored cases
* `list_page.dart`: unrelated side effect for an empty list of lists
* `match.dart`: added a computation of the status at the attribute level
* `personalized_ranking_page.dart`: refactored the colors; now using the new `UserPreferencesView.showModel` method
* `product_page.dart`: now displaying a distinct item for each selected attribute
* `profile_page.dart`: now using the new `UserPreferencesView.showModel` method
* `smooth_expandable_card.dart`: now using the new `SmoothCard` widget
* `smooth_it_model.dart`: added a conversion tool between bool and int indices
* `user_contribution_model.dart`: unrelated refactoring
* `user_preferences_view.dart`: added a useful …
> feature/#120 - enhanced product page

- packages/smooth_app/lib/pages/product_page.dart
- packages/smooth_app/pubspec.yaml
* `product_page.dart`: added a "share" bottom button
* `pubspec.yaml`: added library `wc_flutter_share`, in order to share text
> feature/#122 - "share product" button

- packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
- packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
- packages/smooth_app/lib/data_models/user_preferences_model.dart
- packages/smooth_app/lib/database/dao_product_list.dart
- packages/smooth_app/lib/pages/list_page.dart
- packages/smooth_app/lib/pages/product_list_page.dart
- packages/smooth_app/lib/pages/product_page.dart
- packages/smooth_app/lib/temp/user_preferences.dart
* `attribute_list_expandable.dart`: unrelated fix for #131
* `dao_product_list.dart`: added methods `clear` and `paste`
* `list_page.dart`: refactoring
* `product_list_page.dart`: added a Swipe+Dismissible effect on user lists; added a BottomNavigationBar to copy/paste/clear/delete
* `product_page.dart`: made public the `showLists` method
* `smooth_product_card_found.dart`: long press triggers the display of the lists the product belongs to
* `user_preferences.dart`: added a preference for "copy/paste"
* `user_preferences_model.dart`: added method `getReferenceAttribute`
> feature/#21_5 - product list page with copy/paste/clear/delete and swipe/dismiss

- packages/smooth_app/lib/pages/choose_page.dart
- packages/smooth_app/lib/themes/smooth_theme.dart
- packages/smooth_ui_library/lib/widgets/smooth_listTile.dart
Updated the background color + smooth_listTile for better contrast.
Changed files:
`smooth_theme.dart`: Added `backgroundcolor` to `colorScheme`
`smooth_listTile.dart`: Switched from `container` to `card` for use of elevation
`choose_page.dart`: formatting
> UI contrast

- packages/smooth_app/lib/database/keywords_product_query.dart
- packages/smooth_app/lib/pages/choose_page.dart
- packages/smooth_app/pubspec.yaml
* `choose_page.dart`: added the country code parameter when calling `KeywordsProductQuery`
* `keywords_product_query.dart`: replaced `language` parameter by `lc` and `cc`; refactored
* `pubspec.yaml`: upgraded `openfoodfacts` to brand new version `^0.3.15`
> feature/#133 - added country code parameter for keyword search

- packages/smooth_app/lib/pages/product_page.dart
Impacted file:
* `product_page.dart`: fixed preferences icon color, uniformed the caps, added opacity for colored items in dark mode
> bug/#159 - fixed product page colors

- packages/smooth_app/lib/pages/home_page.dart
- packages/smooth_app/lib/pages/product_list_button.dart
New file:
* `product_list_button.dart`: nice looking button for a product list
Impacted file:
* `home_page.dart`: the product lists are now directly accessible via nice looking buttons
> feature/#167 - nice looking buttons for product lists

- packages/smooth_app/lib/pages/home_page.dart
- packages/smooth_app/lib/pages/product_query_page_helper.dart
* `home_page.dart`: the white bear left a paw print on the app bar; moved to the bottom "food category search" and "search history"; displayed the preferences as rounded rects
* `product_query_page_helper.dart`: minor text change
> feature/#164 - one step closer to the white bear

- packages/smooth_app/lib/pages/pantry_page.dart
Impacted file:
* `pantry_page.dart`
> feature/#166 - added a "no date" option for pantries

- packages/smooth_app/lib/data_models/pantry.dart
- packages/smooth_app/lib/pages/home_page.dart
- packages/smooth_app/lib/pages/pantry_button.dart
- packages/smooth_app/lib/pages/pantry_dialog_helper.dart
- packages/smooth_app/lib/pages/pantry_list_page.dart
- packages/smooth_app/lib/pages/pantry_page.dart
- packages/smooth_app/lib/temp/user_preferences.dart
* `home_page.dart`: now displays the new pantry type: shopping lists
* `pantry.dart`: introduced a new pantry type: shopping lists, and their icons
* `pantry_button.dart`: displays differently regular pantries and shopping lists
* `pantry_dialog_helper.dart`: different labels for pantries and shopping lists
* `pantry_list_page.dart`: works for pantries and shopping lists
* `pantry_page.dart`: different display for pantries and shopping lists
* `user_preferences.dart`: now gets/puts data about the new pantry type: shopping lists
> feature_2/#166 - now we have shopping lists (pantries without dates)

- packages/smooth_app/lib/data_models/continuous_scan_model.dart
- packages/smooth_app/lib/database/barcode_product_query.dart
- packages/smooth_app/lib/database/keywords_product_query.dart
- packages/smooth_app/lib/database/product_query.dart
- packages/smooth_app/lib/pages/choose_page.dart
- packages/smooth_app/lib/pages/product_dialog_helper.dart
- packages/smooth_app/lib/pages/product_page.dart
- packages/smooth_app/lib/pages/scan_page.dart
New file:
* `product_dialog_helper.dart`: Dialog helper for product barcode search
* `barcode_product_query.dart`: unrelated refactoring of the use of language and country codes
* `choose_page.dart`: moved the "barcode search dialog" to new class `ProductDialogHelper`
* `continuous_scan_model.dart`: unrelated refactoring of the use of language and country codes
* `keywords_product_query.dart`: unrelated minor refactoring
* `product_page.dart`: added a "refresh product" button on the bottom bar
* `product_query.dart`: : unrelated adding of methods for the language and country codes; added translated fields
* `scan_page.dart`: unrelated refactoring of the use of language and country codes
> feature/#178 - refresh button on bottom bar of product page

- packages/smooth_app/lib/cards/product_cards/product_list_preview_helper.dart
> Prefer const with constant constructors fix (#184)

- packages/smooth_app/lib/cards/product_cards/pantry_preview.dart
- packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
Impacted file:
* `pantry_preview.dart`
* `product_list_preview.dart`
> bug/#213 - replaced the misleading "..." with a forward arrow

- packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
Impacted file:
* `attribute_list_expandable.dart`
> bug/#202 - systematically show title for paragraphs on product page

- packages/smooth_app/lib/pages/product_list_page.dart
Impacted file:
* `product_list_page.dart`
> feature/#238 - added a "web" bottom button on product list page to OFF website

- packages/smooth_app/lib/pages/home_page.dart
Impacted file:
* `home_page.dart`
> bug/#250 - "add food list" button should not be in history food lists

- .github/workflows/web-release.yml
> web version bump and delayed web

- packages/smooth_app/lib/pages/product/product_page.dart
As suggested by @monsieurtanuki , replacing the carousel_slider plugin with a simple horizontal ListView. Works perfectly. :)
Fixes #261
> replace carousel_slider with horizontal ListView, fixes #261

- packages/smooth_ui_library/lib/widgets/smooth_card.dart
> null-value-in-column's-children-fix #270

- packages/smooth_app/lib/cards/data_cards/image_upload_card.dart
- packages/smooth_app/lib/cards/product_cards/pantry_preview.dart
- packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
- packages/smooth_app/lib/cards/product_cards/product_list_preview_helper.dart
- packages/smooth_app/lib/cards/product_cards/smooth_product_card_edit.dart
- packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
- packages/smooth_app/lib/cards/product_cards/smooth_product_card_not_found.dart
- packages/smooth_app/lib/pages/choose_page.dart
- packages/smooth_app/lib/pages/contribution_page.dart
- packages/smooth_app/lib/pages/home_page.dart
- packages/smooth_app/lib/pages/pantry/common/pantry_button.dart
- packages/smooth_app/lib/pages/pantry/common/pantry_dialog_helper.dart
- packages/smooth_app/lib/pages/product/common/product_list_button.dart
- packages/smooth_app/lib/pages/product/common/product_list_dialog_helper.dart
- packages/smooth_app/lib/pages/product/common/product_list_page.dart
- packages/smooth_app/lib/pages/product/common/product_query_page.dart
- packages/smooth_app/lib/pages/product/common/product_query_page_helper.dart
- packages/smooth_app/lib/pages/scan/continuous_scan_page.dart
- packages/smooth_app/lib/pages/scan/scan_page.dart
`Navigator.push<dynamic>` => `Navigator.push<Widget>`
`MaterialPageRoute<dynamic>` => `MaterialPageRoute<Widget>`
Removed `setState(() {})` after navigation
> cleaned navigaton

- packages/smooth_app/lib/data_models/continuous_scan_model.dart
- packages/smooth_app/lib/data_models/product_list.dart
- packages/smooth_app/lib/database/product_query.dart
@monsieurtanuki : as discussed in #178 , when a product is scanned, I'd like to first show the cached result if we have one (as it's done today), but in parallel I'd like to launch a query to refresh it. I can launch the query, but I'm having trouble to update the product card and to update the database. Could you take a look?
> trying to refresh scanned products #178 (work in progress) (does not work yet)

- packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart
- packages/smooth_ui_library/lib/animations/smooth_animated_collapse_arrow.dart
- packages/smooth_ui_library/lib/widgets/smooth_card.dart
- packages/smooth_ui_library/lib/widgets/smooth_expandable_card.dart
The CollapseArrow is now a own widget in the productPage and the preferences.
Added animation to the preferences.
> AnimatedCollapseArrow extended

- packages/smooth_app/lib/pages/home_page.dart
> Food ranking params limitation

- packages/smooth_app/lib/l10n/app_en.arb
- packages/smooth_app/lib/pages/product/common/product_query_page.dart
- packages/smooth_app/lib/pages/product/common/product_query_page_helper.dart
- packages/smooth_app/pubspec.yaml
For #317
The different plural forms are now passed as value and the translators now have more possibilities to adjust the sentence structure.
> Better plural support

- packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
- packages/smooth_app/lib/data_models/product_list.dart
- packages/smooth_app/lib/pages/home_page.dart
- packages/smooth_app/lib/pages/list_page.dart
- packages/smooth_app/lib/pages/pantry/common/pantry_button.dart
- packages/smooth_app/lib/pages/pantry/common/pantry_list_page.dart
- packages/smooth_app/lib/pages/product/common/product_list_button.dart
- packages/smooth_app/lib/pages/product/common/smooth_chip.dart
- packages/smooth_app/lib/pages/product_copy_helper.dart
- packages/smooth_app/lib/pages/text_search_widget.dart
New file:
* `smooth_chip.dart`: Typical action button for Smoothie
* `home_page.dart`: now displaying lists horizontally instead of wraps; minor refactoring; minor UI adjustment
* `list_page.dart`: minor refactoring
* `pantry_button.dart`: now relying on new widget `SmoothChip`
* `pantry_list_page.dart`: minor refactoring
* `product_copy_helper.dart`: minor refactoring
* `product_list.dart`: minor refactoring
* `product_list_button.dart`: now relying on new widget `SmoothChip`
* `product_list_preview.dart`: minor UI adjustment
* `text_search_widget.dart`: minor UI adjustment
> feature/#326 - displays lists horizontally in home screen

- packages/smooth_app/lib/data_models/product_preferences.dart
- packages/smooth_app/lib/pages/home_page.dart
* `home_page.dart`: click on food parameter in home page goes to specific dialog
* `product_preferences.dart`: added helper method `getAttributeGroup`
> feature/#211 - click on food parameter in home page goes to specific dialog

- packages/smooth_app/lib/main.dart
- packages/smooth_app/lib/pages/text_search_widget.dart
- packages/smooth_app/lib/themes/smooth_theme.dart
- packages/smooth_app/pubspec.yaml
- packages/smooth_ui_library/lib/buttons/smooth_simple_button.dart
> Minor changes

- packages/smooth_app/ios/fastlane/Fastfile
> Temporary fastfile fix

- packages/smooth_app/ios/fastlane/Fastfile
> Temporary ios version code

- packages/smooth_app/lib/pages/product/product_page.dart
Impacted file:
* `product_page.dart`: changed the subtitle; moved 2 items from bottom action bar to app bar
@teolemon A quick fix in your direction:
> feature/#204 - simplified bottom action bar + other UI changes
