openfoodfacts/smooth-app

packages/smooth_app/analysis_options.yaml
packages/smooth_app/ios/Runner/Info.plist
packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart
packages/smooth_app/lib/generated/intl/messages_all.dart
packages/smooth_app/lib/generated/intl/messages_en.dart
packages/smooth_app/lib/generated/intl/messages_ja.dart
packages/smooth_app/lib/generated/intl/messages_zh_Hant.dart
packages/smooth_app/lib/generated/l10n.dart
packages/smooth_app/lib/l10n/intl_en.arb
packages/smooth_app/lib/l10n/intl_ja.arb
packages/smooth_app/lib/l10n/intl_zh_Hant.arb
packages/smooth_app/lib/main.dart
packages/smooth_app/lib/pages/choose_page.dart
packages/smooth_app/lib/pages/collaboration_page.dart
packages/smooth_app/lib/pages/organization_page.dart
packages/smooth_app/lib/pages/profile_page.dart
packages/smooth_app/lib/pages/tracking_page.dart
packages/smooth_app/pubspec.yaml

This provides a bare bones implementation using [intl](https://pub.dev/packages/intl) package and [Flutter Intl](https://plugins.jetbrains.com/plugin/13666-flutter-intl) plugin to make it easier to localize the app down the road.
* use `intl` as suggested in the [offical docs](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) to enable internationalization
* use [this IDE plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl) to generate boilerplate code for translations
* add translations for Japanese and Traditional Chinese (to check things work as expected)
* code formatting

Add internationalization package to prepare for localization

---

packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart

Impacted file:
* `user_preferences_view.dart`: now we don't call `this.callback` if it's `null`

bug/#27 - UserPreferencesView silent crash fix

---

packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart
packages/smooth_app/lib/data_models/user_preferences_model.dart
packages/smooth_app/lib/main.dart
packages/smooth_app/lib/temp/user_preferences.dart
packages/smooth_ui_library/lib/buttons/smooth_main_button.dart

* `main.dart`: added an "init" of preferences
* `smooth_main_button.dart`: added parameters in order to add flexibility to color ("is it an important button?") and to width (e.g. 2 buttons on the same row)
* `user_preferences.dart`: added `init` and `resetImportances` methods
* `user_preferences_model.dart`: refactored
* `user_preferences_view.dart`: added a "reset preferences" button

feature/#31_2 - added "reset preferences" button and "init preferences"

---

packages/smooth_app/lib/cards/category_cards/attribute_card.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_edit.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_loading.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_not_found.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_template.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_thanks.dart
packages/smooth_app/lib/data_models/continuous_scan_model.dart
packages/smooth_app/lib/data_models/user_preferences_model.dart
packages/smooth_app/lib/lists/smooth_product_carousel.dart

… and in the correct order
New file:
* `attribute_card.dart`: displays the svg of the score of the product for the variable
Deleted file:
* `smooth_product_card_template.dart`: replaced implicitly with `Widget`
* `continuous_scan_model.dart`: refactoring around the now deleted "template"
* `smooth_product_card_edit.dart`: refactoring around the now deleted "template"
* `smooth_product_card_found.dart`: display only the preferences important attribute's svg of a product, and in the correct order
* `smooth_product_card_loading.dart`: refactoring around the now deleted "template"
* `smooth_product_card_not_found.dart`: refactoring around the now deleted "template"
* `smooth_product_card_thanks.dart`: refactoring around the now deleted "template"
* …

feature/#32 - display only the preferences important attribute's svg of a product

---

packages/smooth_app/lib/data_models/continuous_scan_model.dart
packages/smooth_app/lib/data_models/database_product_list_supplier.dart
packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/data_models/product_list_supplier.dart
packages/smooth_app/lib/data_models/product_query_model.dart
packages/smooth_app/lib/data_models/query_product_list_supplier.dart
packages/smooth_app/lib/database/dao_product.dart
packages/smooth_app/lib/database/dao_product_list.dart
packages/smooth_app/lib/database/group_product_query.dart
packages/smooth_app/lib/database/keywords_product_query.dart
packages/smooth_app/lib/database/local_database.dart
packages/smooth_app/lib/database/product_query.dart
packages/smooth_app/lib/pages/choose_page.dart
packages/smooth_app/lib/pages/product_query_page.dart
packages/smooth_app/lib/pages/product_query_page_helper.dart

... and automagically asking the end-user if they want to see the cache
New files:
* `dao_product.dart`
* `dao_product_list.dart`
* `database_product_list_supplier.dart`
* `product_list.dart`
* `product_list_supplier.dart`
* `product_query_page_helper.dart`
* `query_product_list_supplier.dart`
* `choose_page.dart`: now uses `ProductQueryPageHelper` in order to get database or http results; refactored
* `continuous_scan_model.dart`: minor refactoring due to DAO
* `group_product_query.dart`: now implements new method `getProductList`
* `keywords_product_query.dart`: now implements new method `getProductList`
* `local_database.dart`: now it's version 2; refactored using the new DAO classes
* `product_query.dart`: new method `getProductList`
* `product_query_model.dart`: now …

feature/#21 - automatically storing keywords and group results into the database

---

packages/smooth_app/lib/data_models/database_product_list_supplier.dart
packages/smooth_app/lib/data_models/product_list_supplier.dart
packages/smooth_app/lib/data_models/query_product_list_supplier.dart
packages/smooth_app/lib/pages/product_query_page.dart
packages/smooth_app/lib/pages/product_query_page_helper.dart

* `database_product_list_supplier.dart`: implemented new method `getRefreshSupplier()`
* `product_list_supplier.dart`: added method `getRefreshSupplier()`
* `product_query_page.dart`: added a snack bar - for refreshment
* `product_query_page_helper.dart`: remove the alert dialog and moved the logic to `ProductQueryPage`
* `query_product_list_supplier.dart`: implemented new method `getRefreshSupplier()`

feature/#87 - immediate access to database data, with a snackbar for http refresh

---

packages/smooth_app/lib/data_models/continuous_scan_model.dart
packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/data_models/smooth_it_model.dart
packages/smooth_app/lib/database/local_database.dart
packages/smooth_app/lib/lists/smooth_product_carousel.dart
packages/smooth_app/lib/main.dart
packages/smooth_app/lib/pages/alternative_continuous_scan_page.dart
packages/smooth_app/lib/pages/continuous_scan_page.dart
packages/smooth_app/lib/pages/contribution_page.dart
packages/smooth_app/lib/pages/personalized_ranking_page.dart
packages/smooth_app/lib/pages/product_page.dart
packages/smooth_app/lib/pages/product_query_page.dart
packages/smooth_app/lib/pages/scan_page.dart

New file:
* `scan_page.dart`: helper class to be used on top of `AlternativeContinuousScanPage` and `ContinuousScanPage`
* `alternative_continuous_scan_page.dart`: `ContinuousScanModel` is now initialized upstream by `ScanPage`
* `continuous_scan_model.dart`: now a `ChangeNotifier`, uses a `ProductList` and database cache
* `continuous_scan_page.dart`: `ContinuousScanModel` is now initialized upstream by `ScanPage`
* `contribution_page.dart`: uses the new `ScanPage` widget instead of the 2 scan pages
* `local_database.dart`: removed the dummy notify listener method
* `main.dart`: uses the new `ScanPage` widget instead of the 2 scan pages
* `personalized_ranking_page.dart`: now we use a `ProductList` as input
* `product_list.dart`: added a `getProduct` method and a "scan …

feature/#21 - scan now uses local database, for product look up and for its history

---

.github/FUNDING.yml
.github/workflows/ci.yml
packages/smooth_app/android/gradle/wrapper/gradle-wrapper.properties
packages/smooth_app/lib/pages/choose_page.dart
packages/smooth_app/lib/themes/smooth_theme.dart

Added: 
`FUNDING.yml `
`ci.yml`
FUNDING just provides links to support OFF in the github repo and ci.yml is a workflow which tests whether new pull requests work

GitHub specials

---

packages/smooth_app/lib/bottom_sheet_views/user_preferences_view.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_loading.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_not_found.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_thanks.dart
packages/smooth_app/lib/main.dart
packages/smooth_app/lib/pages/choose_page.dart
packages/smooth_app/lib/pages/personalized_ranking_page.dart
packages/smooth_app/lib/pages/product_page.dart
packages/smooth_app/lib/themes/smooth_theme.dart
packages/smooth_ui_library/lib/widgets/smooth_expandable_card.dart
packages/smooth_ui_library/lib/widgets/smooth_listTile.dart
packages/smooth_ui_library/lib/widgets/smooth_search_bar.dart

* `main.dart`: refactored
* `personalized_ranking_page.dart`: now transparently using the default values for `BottomNavigationBar`
* `product_page.dart`: replaced `themeData.cardColor` with `themeData.colorScheme.surface`
* `smooth_expandable_card.dart`: replaced `themeData.cardColor` with `themeData.colorScheme.surface`
* `smooth_listTile.dart`: replaced `themeData.cardColor` with `themeData.colorScheme.surface`
* `smooth_product_card_loading.dart`: replaced `themeData.cardColor` with `themeData.colorScheme.surface`
* `smooth_product_card_not_found.dart`: replaced `themeData.cardColor` with `themeData.colorScheme.surface`
* `smooth_product_card_thanks.dart`: replaced `themeData.cardColor` with `themeData.colorScheme.surface`
* `smooth_search_bar.dart`: replaced …

ColorScheme refactoring: simplification by relying on the default colors

---

packages/smooth_app/lib/pages/alternative_continuous_scan_page.dart
packages/smooth_app/lib/pages/continuous_scan_page.dart

Added a backbutton to a transparent `appBar` to the `continuous_scan_page` and `alternative_continuous_scan_page`, for navigation on Iphone #17.

Added backbutton to scanner

---

packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
packages/smooth_app/lib/data_models/match.dart
packages/smooth_app/lib/pages/product_page.dart

This is a fix for #131, to handle the case where the user has selected some attributes in the preferences, and that some of those attributes are not available in some products. (e.g. if the Eco-Score is not available for a specific country).
Affected files:
- attribute_list_expandable.dart : do not add a card for the attribute if it is null
- match.dart : replaced getAttributeMatches with getMatchingAttributes to get a map of attributes instead of a map of match scores
- product_page.dart: as we have a separate AttributeList for each attribute, we now do not display the AttributeList if the only attribute it contains is null (otherwise we get an empty card).

Issue 131/undefined attribute

---

packages/smooth_app/lib/data_models/match.dart
packages/smooth_app/lib/pages/product_page.dart

info • The value of the field '_KNOWN_STATUS' isn't used •
lib/data_models/match.dart:47:23 • unused_field
info • Only use double quotes for strings containing single quotes •
lib/pages/product_page.dart:378:29 • prefer_single_quotes

bug/#136 - fixed info minor issues

---

packages/smooth_app/lib/cards/data_cards/image_upload_card.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_not_found.dart
packages/smooth_app/lib/lists/smooth_product_carousel.dart
packages/smooth_app/lib/pages/product_page.dart

Related issue: #86 
When a product is not found in OFF, the app currently opens a SmoothUploadPage.
I think it would be best to do it differently, and to open a ProductPage (just like when we do find the product in OFF), so that we can benefit from all the features associated with it (e.g. the lists).
This is what this PR does:
- new image_upload_card.dart : currently just a button to take, crop, and upload a photo (front, ingredients etc.). Not beautiful, but working.
- smooth_product_card_not_found.dart : now creates a new Product instance, and open a ProductPage on it
- product_page.dart : separate the parts that are common to both existing products and new products (e.g. the navigation and bottom bars), and creates 2 methods _buildProductBody()  (with the existing code), and …

Start of refactoring of new product page, with image upload

---

packages/smooth_app/lib/database/dao_product_list.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/product_list_dialog_helper.dart
packages/smooth_app/lib/pages/product_list_page.dart
packages/smooth_app/lib/pages/product_query_page_helper.dart

New file:
* `product_list_dialog_helper.dart`: centralizing the dialogs for product lists
* `dao_product_list.dart`: added method `rename`
* `list_page.dart`: now using the new ProductListDialogHelper class; minor refactoring
* `product_list_page.dart`: added a "rename" top action; moved "delete" to top; added a "grocery" bottom action; now using the new ProductListDialogHelper class
* `product_query_page_helper.dart`: minor presentation refactoring

feature/#21_6 - user product lists can now be renamed and exported as grocery lists

---

packages/smooth_app/android/app/src/main/AndroidManifest.xml
packages/smooth_app/ios/Runner/Info.plist
packages/smooth_app/pubspec.yaml

fixes #153 
solution from https://greymag.medium.com/flutter-orientation-lock-portrait-only-c98910ebd769

lock the orientation in portrait mode, fixes #153

---

packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/database/dao_product_list.dart
packages/smooth_app/lib/database/local_database.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/product_list_dialog_helper.dart
packages/smooth_app/lib/pages/product_list_page.dart
packages/smooth_app/lib/themes/smooth_theme.dart

* `dao_product_list.dart`: created the new `product_list_extra` table and accessed it
* `home_page.dart`: not 100% unrelated - now using new method `SmoothTheme.getForegroundColor`
* `list_page.dart`: added the background color to the product list card
* `local_database.dart`: upgraded to version 3, in order to create the new `product_list_extra` table
* `product_list.dart`: added extraTags field (for the moment, icon and color)
* `product_list_dialog_helper.dart`: added method `openChange`; minor refactoring
* `product_list_page.dart`: added the background color and the icon to the app bar, added the change icon menu item
* `smooth_theme.dart`: not 100% related - added methods `getForegroundColor` and `getBackgroundColor` in order to get unified shades

feature/#148 - added editable icon and color to product lists

---

packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
packages/smooth_app/lib/database/dao_product_list.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/product_list_dialog_helper.dart
packages/smooth_app/lib/pages/product_list_page.dart
packages/smooth_app/lib/pages/product_query_page_helper.dart

New file:
* `product_list_preview.dart`: widget that computes and displays the first products of a list
* `dao_product_list.dart`: added a 'bool unique' parameter to "first products" query
* `home_page.dart`: now using new widget `ProductListPreview` to display history
* `list_page.dart`: now using new widget `ProductListPreview` to display product lists
* `product_list_dialog_helper.dart`: unrelated minor bug fix
* `product_list_page.dart`: unrelated minor bug fix
* `product_query_page_helper.dart`: minor refactoring

feature/#146 - the product lists are now displayed with a preview of products

---

packages/smooth_app/lib/cards/product_cards/pantry_preview.dart
packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
packages/smooth_app/lib/cards/product_cards/product_list_preview_helper.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
packages/smooth_app/lib/data_models/pantry.dart
packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/database/dao_product_list.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/pantry_button.dart
packages/smooth_app/lib/pages/pantry_dialog_helper.dart
packages/smooth_app/lib/pages/pantry_list_page.dart
packages/smooth_app/lib/pages/pantry_page.dart
packages/smooth_app/lib/temp/user_preferences.dart

For the moment, in order to copy products to a pantry:
* go to a product list
* click on the "copy" button (bottom bar)
* go to the pantry
* click on the "paste" button (bottom bar)
New files:
* `pantry.dart`: a pantry (name, color, icon, list of barcodes with quantity and dates)
* `pantry_button.dart`: a button for a pantry, with the corresponding color, icon, name and shape
* `pantry_dialog_helper.dart`: a dialog helper for pantries
* `pantry_list_page.dart`: a page where all the pantries are displayed as previews
* `pantry_page.dart`: a page for one pantry where we can change all the data
* `pantry_preview.dart`: a preview button for a pantry, with its N first products
* `product_list_view_helper.dart`: a preview button for a list of products; used to be private in ProductListPreview …

feature/#164_2 - pantries are now available

---

packages/smooth_app/lib/cards/product_cards/product_list_preview_helper.dart

Return an empty widget in ProductListPreviewHelper's build function when the input list is null

---

packages/smooth_app/lib/cards/product_cards/product_list_preview_helper.dart
packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/database/category_product_query.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/product_list_page.dart
packages/smooth_app/lib/pages/product_page.dart
packages/smooth_app/lib/pages/product_query_page_helper.dart

From the bottom of the product page. It's ugly for the moment, it's just a feature suggestion. Any idea?
New file:
* `category_product_query.dart`: Product query dedicated to category (e.g. 'en:mueslis-with-fruits')
* `home_page.dart`: added the category search to the search history
* `product_list.dart`: added the category search
* `product_list_page.dart`: added the category search
* `product_list_preview_helper.dart`: unrelated minor refactoring
* `product_page.dart`: added lousy clickable categories at the end of the product page, just to see
* `product_query_page_helper.dart`: added the category search

feature/#23 - added the "similar product" / category search

---

packages/smooth_app/lib/cards/product_cards/pantry_preview.dart
packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
packages/smooth_app/lib/data_models/pantry.dart
packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/pages/choose_page.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/pantry_button.dart
packages/smooth_app/lib/pages/pantry_dialog_helper.dart
packages/smooth_app/lib/pages/pantry_list_page.dart
packages/smooth_app/lib/pages/pantry_page.dart
packages/smooth_app/lib/pages/personalized_ranking_page.dart
packages/smooth_app/lib/pages/product_list_button.dart
packages/smooth_app/lib/pages/product_list_dialog_helper.dart
packages/smooth_app/lib/pages/product_list_page.dart
packages/smooth_app/lib/pages/product_page.dart
packages/smooth_app/lib/pages/product_query_page.dart
packages/smooth_app/lib/pages/profile_page.dart
packages/smooth_app/lib/themes/smooth_theme.dart

The main change is in `smooth_theme.dart`. Everything comes from there.
* `choose_page.dart`: simplified
* `home_page.dart`: simplified; used the new method `SmoothTheme.getColor`
* `list_page.dart`: simplified
* `pantry.dart`: used the new method `SmoothTheme.getColor`
* `pantry_button.dart`: used the new method `SmoothTheme.getColor`
* `pantry_dialog_helper.dart`: used the new method `SmoothTheme.getColor`
* `pantry_list_page.dart`
* `pantry_page.dart`: simplified; used the new method `SmoothTheme.getColor`
* `pantry_preview.dart`: used the new method `SmoothTheme.getColor`
* `personalized_ranking_page.dart`: simplified; used the new method `SmoothTheme.getColor`
* `product_list.dart`: used the new method `SmoothTheme.getColor`
* `product_list_button.dart`: used the new …

feature/#198 - switched to a simpler (and closer to defaults) color management

---

packages/smooth_app/lib/database/dao_product.dart
packages/smooth_app/lib/pages/home_page.dart

Implemented a look-up on the local database, and linked it to the text field.
For the moment, the matching products are only printed in the console.
The next step would be to display the results with an autocomplete text field.
* `dao_product.dart`: new method `List<Product> getSuggestions(String)`
* `home_page.dart`: added an `onUpdate` method on the text field to print the products that match locally

feature/#147 - local look-up - first step towards autocomplete text field

---

packages/smooth_app/pubspec.yaml

> Because smooth_app depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
> So, because smooth_app depends on intl ^0.16.1, version solving failed.
> pub get failed (1; So, because smooth_app depends on intl ^0.16.1, version solving failed.)

intl version fix

---

packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/pubspec.yaml

@monsieurtanuki search as you type is now working, but at the time its not that nice to use. 
When you tap outside of the bounds of the proposals they are still visible.
This is a known problem, an issue with a couple of suggestions as a workaround can be found [here](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/169).
Should we use one of these suggestions or do you have a better idea

Search as you type

---

packages/smooth_app/lib/temp/user_preferences.dart

Impacted file:
* `user_preferences.dart`: now using `SharedPreferences.remove()` instead of `SharedPreferences.set___(, null)`

bug/#233 - don't set a SharedPreferences value to null, remove it

---

packages/smooth_app/ios/Podfile

My assumption is that we used the default Podfile and that nobody ever edited it.
Impacted file:
* `Podfile`: deleted and automatically recreated

bug/#232 - reinit of the Podfile after migration to Flutter 2.0.0

---

packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/product_list_dialog_helper.dart

For empty product lists only for the moment.
* `list_page.dart`: replaced the "Empty" text with an explicit "create a food list" button, which eventually goes to the newly created product page
* `product_list_dialog_helper.dart`: method `openNew` now returns a `ProductList` instead of a simple `bool`

feature/#214 - explicit "create a list" button instead of "empty" text

---

packages/smooth_app/lib/data_models/user_preferences_model.dart
packages/smooth_app/pubspec.yaml
packages/smooth_ui_library/pubspec.yaml

fixes #246
I only upgraded the modules that flutter pub get was complaining about when doing dependency resolution.
Also changed: the new http module now expects an Uri instead of a String in http.get

upgrade openfoodfacts to 1.0.1-beta

---

packages/smooth_app/lib/cards/product_cards/pantry_preview.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/pantry_button.dart
packages/smooth_app/lib/pages/pantry_dialog_helper.dart
packages/smooth_app/lib/pages/pantry_list_page.dart
packages/smooth_app/lib/pages/pantry_page.dart
packages/smooth_app/lib/pages/product_list_dialog_helper.dart

Now available for home page too.
* `home_page.dart`: instead of an "empty" text, always added a "create a list/pantry" from the home page
* `list_page.dart`: minor refactoring
* `pantry_button.dart`: minor refactoring
* `pantry_dialog_helper.dart`: now actually opening the pantry page at the end of `openNew`
* `pantry_list_page.dart`: added a "create list" button instead of "empty" text
* `pantry_page.dart`: minor refactoring
* `pantry_preview.dart`: minor refactoring
* `product_list_dialog_helper.dart`: now actually opening the product page at the end of `openNew`

feature/#214_2 - for pantry/shopping list, "create a list" button instead of "empty" text

---

packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/pantry/common/pantry_list_page.dart
packages/smooth_app/lib/pages/product/product_page.dart
packages/smooth_ui_library/lib/widgets/smooth_card.dart
packages/smooth_ui_library/lib/widgets/smooth_expandable_card.dart

fixes: #203 
Removed collapsed from smooth_card:
`smooth_card.dart `
`attribute_list_expandable.dart`
`list_page.dart `
`pantry_list_page.dart  `
`product_page.dart `
`smooth_expandable_card.dart`: Added icon animation

Product Page section expanding animation

---

packages/smooth_app/lib/cards/expandables/attribute_list_expandable.dart
packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/pantry/common/pantry_list_page.dart
packages/smooth_app/lib/pages/product/product_page.dart
packages/smooth_ui_library/lib/widgets/smooth_card.dart
packages/smooth_ui_library/lib/widgets/smooth_expandable_card.dart

Added padding + insets option to smooth_card and smooth_expandable_card.
The homepage and product_list_preview now use SmoothCard instead of Card.
Before and after comparison
Dark:
<details>
</details>
Light:
<details>
</details>

refactored homepage to use SmoothCard instead of Card

---

packages/smooth_app/lib/data_models/pantry.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/pantry/pantry_page.dart
packages/smooth_app/lib/pages/text_search_widget.dart
packages/smooth_ui_library/lib/widgets/smooth_product_image.dart

New file:
* `text_search_widget.dart`: Local product search by text
* `home_page.dart`: moved text search code to new `TextSearchWidget` class
* `pantry.dart`: renamed method `add` as `addAll`; added method `add` as an "add single item" method
* `pantry_page.dart`: added a `TextSearchWidget` on top of the screen; a product is automatically added after a product page is reached from the search and then pop'ed
* `smooth_product_image.dart`: unrelated fix where width and height are mandatory, and several image front urls are tried

feature/#290 - Local search on pantry page, with product automatically added

---

packages/smooth_app/lib/pages/choose_page.dart
packages/smooth_app/lib/pages/text_search_widget.dart

For some reason the internet lookup was not called anymore.
Now when you type in the product name:
* there's a local lookup
* NEW: there's an additional icon button that launches the API lookup
* `choose_page.dart`: minor fix probably needed from flutter 2.0
* `text_search_widget.dart`: added an "internet search button"

feature/#290_2 - product search with local and API lookup

---

packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
packages/smooth_app/lib/data_models/pantry.dart
packages/smooth_app/lib/pages/pantry/pantry_page.dart

* `pantry.dart`: added the notion of ordered barcodes and the related methods
* `pantry_page.dart`: used a `ReorderableListView` instead of a `ListView`
* `smooth_product_card_found.dart`: added an optional handle `Widget` at the level of the product title

feature/#166_2 - products in pantries are now reorderable, with a drag handle

---

packages/smooth_app/lib/data_models/product_query_model.dart
packages/smooth_app/lib/database/keywords_product_query.dart

* `keywords_product_query.dart`: now using `SearchTerms` instead of `TagFilter`/categories
* `product_query_model.dart`: minor side effect fix

bug/#297 - fixed the keyword search API call

---

packages/smooth_app/lib/database/dao_product.dart
packages/smooth_app/lib/database/local_database.dart
packages/smooth_app/pubspec.yaml

Now works only on the product name(s), too.
Impacted classes:
* `dao_product.dart`: added table `product_extra` for accented character management
* `local_database.dart`: incremented the database version from 3 to 4
* `pubspec.yaml`: added library `diacritic` for accented characters management

bug/#297_2 - case and accent independent local database suggestion lookup

---

packages/smooth_app/lib/cards/product_cards/product_list_preview.dart
packages/smooth_app/lib/cards/product_cards/smooth_product_card_found.dart
packages/smooth_app/lib/data_models/product_list.dart
packages/smooth_app/lib/data_models/user_preferences.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/multi_select_product_page.dart
packages/smooth_app/lib/pages/pantry/common/pantry_button.dart
packages/smooth_app/lib/pages/pantry/pantry_page.dart
packages/smooth_app/lib/pages/product/common/product_list_button.dart
packages/smooth_app/lib/pages/product/common/product_list_dialog_helper.dart
packages/smooth_app/lib/pages/product/common/product_list_page.dart
packages/smooth_app/lib/pages/product/common/product_query_page_helper.dart
packages/smooth_app/lib/pages/product/product_page.dart
packages/smooth_app/lib/pages/product_copy_helper.dart

New files:
* `multi_select_product_page.dart`: Page where products can be selected for copy or removal
* `product_copy_helper.dart`: Helper for product copy as multi selected
* `home_page.dart`: minor refactoring
* `pantry_button.dart`: added optional `onPressed` constructor parameter
* `pantry_page.dart`: removed bottom navigation bar; long press on a product opens new multi select product page; products are now dismissible
* `product_list.dart`: added method `getOrderedBarcodes`
* `product_list_button.dart`: added optional `onPressed` constructor parameter
* `product_list_dialog_helper.dart`: simplified call to `ProductListPage`
* `product_list_page.dart`: simplified constructor parameters; removed bottom navigation bar; long press on a product opens new multi select …

feature/#216 - multi select product copy from lists + single product copy

---

packages/smooth_app/lib/data_models/pantry.dart
packages/smooth_app/lib/pages/pantry/common/pantry_dialog_helper.dart

The problem is that default value for constructor parameters must be `const`.
And one parameter, by default, would be `<String>[]` (where items can be added).
Which is not the same as `const <String>[]` (where nothing can be changed).

bug/#322 - tricky dart fix

---

packages/smooth_app/lib/cards/product_cards/pantry_preview.dart
packages/smooth_app/lib/data_models/pantry.dart
packages/smooth_app/lib/pages/home_page.dart
packages/smooth_app/lib/pages/list_page.dart
packages/smooth_app/lib/pages/multi_select_product_page.dart
packages/smooth_app/lib/pages/pantry/common/pantry_button.dart
packages/smooth_app/lib/pages/pantry/common/pantry_dialog_helper.dart
packages/smooth_app/lib/pages/pantry/common/pantry_list_page.dart
packages/smooth_app/lib/pages/pantry/pantry_page.dart
packages/smooth_app/lib/pages/product/common/product_list_button.dart
packages/smooth_app/lib/pages/product/common/product_list_dialog_helper.dart
packages/smooth_app/lib/pages/product/product_page.dart
packages/smooth_app/lib/pages/product_copy_helper.dart

* `home_page.dart`: impact of `ProductListButton` and `PantryButton` refactoring; minor refactoring
* `list_page.dart`: impact of `ProductListButton` refactoring; minor refactoring
* `multi_select_product_page.dart`: minor refactoring
* `pantry.dart`: created a constructor for new empty instance
* `pantry_button.dart`: created a constructor for "add pantry"
* `pantry_dialog_helper.dart`: added flexibility to `openNew`; minor refactoring
* `pantry_list_page.dart`: impact of `PantryButton` refactoring; minor refactoring
* `pantry_page.dart`: replaced the `index` and `PantryType` constructor parameters with the more understandable `Pantry` parameter
* `pantry_preview.dart`: minor impact from `PantryPage` new constructor parameters
* `product_copy_helper.dart`: now we manage …

feature/#216_2 - "new pantry/product list" buttons visible at product copy time

---

packages/smooth_app/lib/pages/home_page.dart

In `home_page.dart` I've just commented code that is temporarily not used.
I guess some day we'll use pantries and shopping lists again.
Alternate solutions are:
* remove the code altogether instead of commenting it
* setting up a more relaxed check regarding warnings

bug/#364 - commented pantries and shopping lists code in home page
